### ISSUE TITLE
After successful installation, the startup is invalid

### ISSUE THREAD

**Issue by Minor-fun** [sbwml/luci-app-airconnect#2]
![QQ截图20230930122913](https://github.com/sbwml/luci-app-airconnect/assets/45744798/36083d2e-91b9-4218-bc1d-e30dd7a861e6)
![QQ截图20230930122902](https://github.com/sbwml/luci-app-airconnect/assets/45744798/dc1e6633-84b4-4c97-8d91-f49ae7149010)
Hello, I installed version 1.2.2 of the A9 installation package, but it did not take effect after startup. May I know where the problem is？

**Comment by sbwml** [comment]
airconnect 无法通过源码的方式构建，目前它的二进制来自上游的静态构建，你可以在终端执行以下命令，看看是否二进制文件出现了问题。

```shell
/usr/bin/airupnp -l 1000:2000 -Z -b br-lan
```

**Comment by Minor-fun** [comment]
![QQ截图20231002153241](https://github.com/sbwml/luci-app-airconnect/assets/45744798/67f23109-d078-4980-aab3-d702ff0b38b4)
终端输入上面的这段命令提示Illegal instruction
安装的是下图软件包
![QQ截图20231002154724](https://github.com/sbwml/luci-app-airconnect/assets/45744798/01accb41-21a6-45cb-ade2-a9bdd923ded8)

**Comment by sbwml** [comment]
二进制不兼容，这种问题无解，除非上游额外给这个架构提供二进制，不然就是无解，因为 airconnect 根本无法从源码构建。
